version: ~> 2.1

language: go

os: linux

dist: bionic

osx_image: xcode11.3

jobs:
  fast_finish: true
  include:
    - name: "linux-amd64 (go 1.11.x)"
      go: "1.11.x"
      arch: amd64
      os: linux
      compiler: gcc
      env:
        - platform="linux-amd64"
    - name: "linux-386 (go 1.11.x)"
      go: "1.11.x"
      arch: amd64
      os: linux
      compiler: gcc
      env:
        - platform="linux-386"
        - cross="i686-linux-gnu-"
        - mach="i386"
        - setarch="setarch i386 --verbose --32bit"
      before_install:
        - sudo dpkg --add-architecture i386
        - sudo apt -yq update
        - sudo apt -yq install gcc-multilib
    - name: "linux-arm64 (go 1.11.x)"
      go: "1.11.x"
      arch: arm64
      os: linux
      compiler: gcc
      env:
        - platform="linux-arm64"
    - name: "linux-arm (go 1.11.x)"
      go: "1.11.x"
      arch: arm64
      os: linux
      compiler: gcc
      env:
        - platform="linux-arm"
        - cross="arm-linux-gnueabihf-"
        - mach="armhf"
        - setarch="setarch linux32 --verbose --32bit"
      before_install:
        - sudo dpkg --add-architecture armhf
        - sudo apt -yq update
        - sudo apt -yq install crossbuild-essential-armhf libc6:armhf
    - name: "darwin-amd64 (go 1.11.x)"
      go: "1.11.x"
      arch: amd64
      os: osx
      compiler: gcc
      env:
        - platform="darwin-amd64"
    - name: "linux-amd64 (go 1.12.x)"
      go: "1.12.x"
      arch: amd64
      os: linux
      compiler: gcc
      env:
        - platform="linux-amd64"
    - name: "linux-386 (go 1.12.x)"
      go: "1.12.x"
      arch: amd64
      os: linux
      compiler: gcc
      env:
        - platform="linux-386"
        - cross="i686-linux-gnu-"
        - mach="i386"
        - setarch="setarch i386 --verbose --32bit"
      before_install:
        - sudo dpkg --add-architecture i386
        - sudo apt -yq update
        - sudo apt -yq install gcc-multilib
    - name: "linux-arm64 (go 1.12.x)"
      go: "1.12.x"
      arch: arm64
      os: linux
      compiler: gcc
      env:
        - platform="linux-arm64"
    - name: "linux-arm (go 1.12.x)"
      go: "1.12.x"
      arch: arm64
      os: linux
      compiler: gcc
      env:
        - platform="linux-arm"
        - cross="arm-linux-gnueabihf-"
        - mach="armhf"
        - setarch="setarch linux32 --verbose --32bit"
      before_install:
        - sudo dpkg --add-architecture armhf
        - sudo apt -yq update
        - sudo apt -yq install crossbuild-essential-armhf libc6:armhf
    - name: "darwin-amd64 (go 1.12.x)"
      go: "1.12.x"
      arch: amd64
      os: osx
      compiler: gcc
      env:
        - platform="darwin-amd64"
    - name: "linux-amd64 (go 1.13.x)"
      go: "1.13.x"
      arch: amd64
      os: linux
      compiler: gcc
      env:
        - platform="linux-amd64"
    - name: "linux-386 (go 1.13.x)"
      go: "1.13.x"
      arch: amd64
      os: linux
      compiler: gcc
      env:
        - platform="linux-386"
        - cross="i686-linux-gnu-"
        - mach="i386"
        - setarch="setarch i386 --verbose --32bit"
      before_install:
        - sudo dpkg --add-architecture i386
        - sudo apt -yq update
        - sudo apt -yq install gcc-multilib
    - name: "linux-arm64 (go 1.13.x)"
      go: "1.13.x"
      arch: arm64
      os: linux
      compiler: gcc
      env:
        - platform="linux-arm64"
    - name: "linux-arm (go 1.13.x)"
      go: "1.13.x"
      arch: arm64
      os: linux
      compiler: gcc
      env:
        - platform="linux-arm"
        - cross="arm-linux-gnueabihf-"
        - mach="armhf"
        - setarch="setarch linux32 --verbose --32bit"
      before_install:
        - sudo dpkg --add-architecture armhf
        - sudo apt -yq update
        - sudo apt -yq install crossbuild-essential-armhf libc6:armhf
    - name: "darwin-amd64 (go 1.13.x)"
      go: "1.13.x"
      arch: amd64
      os: osx
      compiler: gcc
      env:
        - platform="darwin-amd64"
    - name: "linux-amd64 (go 1.14.x)"
      go: "1.14.x"
      arch: amd64
      os: linux
      compiler: gcc
      env:
        - platform="linux-amd64"
    - name: "linux-386 (go 1.14.x)"
      go: "1.14.x"
      arch: amd64
      os: linux
      compiler: gcc
      env:
        - platform="linux-386"
        - cross="i686-linux-gnu-"
        - mach="i386"
        - setarch="setarch i386 --verbose --32bit"
      before_install:
        - sudo dpkg --add-architecture i386
        - sudo apt -yq update
        - sudo apt -yq install gcc-multilib
    - name: "linux-arm64 (go 1.14.x)"
      go: "1.14.x"
      arch: arm64
      os: linux
      compiler: gcc
      env:
        - platform="linux-arm64"
    - name: "linux-arm (go 1.14.x)"
      go: "1.14.x"
      arch: arm64
      os: linux
      compiler: gcc
      env:
        - platform="linux-arm"
        - cross="arm-linux-gnueabihf-"
        - mach="armhf"
        - setarch="setarch linux32 --verbose --32bit"
      before_install:
        - sudo dpkg --add-architecture armhf
        - sudo apt -yq update
        - sudo apt -yq install crossbuild-essential-armhf libc6:armhf
    - name: "darwin-amd64 (go 1.14.x)"
      go: "1.14.x"
      arch: amd64
      os: osx
      compiler: gcc
      env:
        - platform="darwin-amd64"
    - name: "linux-amd64 (go master)"
      go: "master"
      arch: amd64
      os: linux
      compiler: gcc
      env:
        - platform="linux-amd64"
    - name: "linux-386 (go master)"
      go: "master"
      arch: amd64
      os: linux
      compiler: gcc
      env:
        - platform="linux-386"
        - cross="i686-linux-gnu-"
        - mach="i386"
        - setarch="setarch i386 --verbose --32bit"
      before_install:
        - sudo dpkg --add-architecture i386
        - sudo apt -yq update
        - sudo apt -yq install gcc-multilib
    - name: "linux-arm64 (go master)"
      go: "master"
      arch: arm64
      os: linux
      compiler: gcc
      env:
        - platform="linux-arm64"
    - name: "linux-arm (go master)"
      go: "master"
      arch: arm64
      os: linux
      compiler: gcc
      env:
        - platform="linux-arm"
        - cross="arm-linux-gnueabihf-"
        - mach="armhf"
        - setarch="setarch linux32 --verbose --32bit"
      before_install:
        - sudo dpkg --add-architecture armhf
        - sudo apt -yq update
        - sudo apt -yq install crossbuild-essential-armhf libc6:armhf
    - name: "darwin-amd64 (go master)"
      go: "master"
      arch: amd64
      os: osx
      compiler: gcc
      env:
        - platform="darwin-amd64"

script:
  - pushd native/src
  - ${setarch} make platform=${platform} cross=${cross} clean build
  - popd
  - ${setarch} go test -v -short -count=1 -args ./...

