language: go

go:
	- 1.11.x
	- 1.12.x
	- 1.13.x
	- 1.14.x
	- master

arch:
	- amd64

os:
	- linux

env:
	- platform=linux-amd64

script:
	- pushd native/src
	- env(usearch) make platform=env(platform) cross=env(cross) clean build
	- popd
	- env(usearch) go test -v -short -count=1 -args ./...
